
ModLoader.SetupFileHook( "lua/NS2Gamerules.lua", "lua/GorgeRun/GorgeRun_NS2Gamerules.lua", "post" )
ModLoader.SetupFileHook( "lua/AlienTeam.lua", "lua/GorgeRun/GorgeRun_AlienTeam.lua", "post" )
ModLoader.SetupFileHook( "lua/TeamInfo.lua", "lua/GorgeRun/GorgeRun_TeamInfo.lua", "post" )
ModLoader.SetupFileHook( "lua/Balance.lua", "lua/GorgeRun/GorgeRun_Balance.lua", "post" )
ModLoader.SetupFileHook( "lua/TeamJoin.lua", "lua/GorgeRun/GorgeRun_TeamJoin.lua", "post" )
ModLoader.SetupFileHook( "lua/CommandStructure_Server.lua", "lua/GorgeRun/GorgeRun_CommandStructure_Server.lua", "post" )
ModLoader.SetupFileHook( "lua/GUIReadyRoomOrders.lua", "lua/GorgeRun/GorgeRun_GUIReadyRoomOrders.lua", "post" )
ModLoader.SetupFileHook( "lua/NS2ConsoleCommands_Server.lua", "lua/GorgeRun/GorgeRun_NS2ConsoleCommands_Server.lua", "post" )
ModLoader.SetupFileHook( "lua/GUIMinimap.lua", "lua/GorgeRun/GorgeRun_GUIMinimap.lua", "post" )
ModLoader.SetupFileHook( "lua/Weapons/Alien/GorgeTunnelAbility.lua", "lua/GorgeRun/GorgeRun_GorgeTunnelAbility.lua", "post" )
ModLoader.SetupFileHook( "lua/Alien_Server.lua", "lua/GorgeRun/GorgeRun_Alien_Server.lua", "post" )
ModLoader.SetupFileHook( "lua/Hud/GUIPlayerResource.lua", "lua/GorgeRun/GorgeRun_GUIPlayerResource.lua", "post" )
ModLoader.SetupFileHook( "lua/ClientUI.lua", "lua/GorgeRun/GorgeRun_ClientUI.lua", "post" )
ModLoader.SetupFileHook( "lua/Sentry.lua", "lua/GorgeRun/GorgeRun_Sentry.lua", "post" )
ModLoader.SetupFileHook( "lua/BalanceMisc.lua", "lua/GorgeRun/GorgeRun_BalanceMisc.lua", "post" )
ModLoader.SetupFileHook( "lua/Clog.lua", "lua/GorgeRun/GorgeRun_Clog.lua", "post" )
ModLoader.SetupFileHook( "lua/Gamerules.lua", "lua/GorgeRun/GorgeRun_Gamerules.lua", "post" )

